<a href="https://colab.research.google.com/github/BeTris/fake5star/blob/master/fake5star.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install transformers

     |████████████████████████████████| 645kB 2.8MB/s 
     |████████████████████████████████| 3.8MB 12.7MB/s 
     |████████████████████████████████| 1.1MB 36.5MB/s 
     |████████████████████████████████| 890kB 42.4MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=f9c3dbbd95161b1c58f94b55f0da8b2304ab9bb05d69196d18a3639e3a4006b1
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [0]:
#installations

In [0]:
import numpy as np
import pandas as pd
import transformers as ppb
import csv
import torch

In [0]:
df = pd.read_csv("https://raw.githubusercontent.com/BeTris/fake5star/5f492d13658ae3610352fde411ff61d7aa745a98/articles(1).csv", header=None)

In [0]:
df.head()

0  1
0  Zoom will enable waiting rooms by default to s...  1
1  Zoom will enable waiting rooms by default to s...  1
2  Insight closes $9.5B fund to help support port...  1
3  The pandemic is already reshaping tech's misin...  1
4  Senator Asks FTC To Investigate Zoom's 'Decept...  1

In [0]:
print(df[0])

0     Zoom will enable waiting rooms by default to s...
1     Insight closes $9.5B fund to help support port...
2     The pandemic is already reshaping tech's misin...
3     Senator Asks FTC To Investigate Zoom's 'Decept...
4     In Russia, Health Services Struggle As Exasper...
                            ...                        
95    Recalling the polio scare, Charlestown man wan...
96    Walmart To Limit Number Of People Shopping At ...
97    Cops ensuring lockdown attacked in Rajkot, Por...
98    Coronavirus crisis: Mr. President, look at the...
99    Georgia Tech's 1990 Final Four team goes down ...
Name: 0, Length: 100, dtype: object


NameError: ignored

In [0]:
# For DistilBERT:
model_class, tokenizer_class, pretrained_weights = (ppb.DistilBertModel, ppb.DistilBertTokenizer, 'distilbert-base-uncased')

## Want BERT instead of distilBERT? Uncomment the following line:
#model_class, tokenizer_class, pretrained_weights = (ppb.BertModel, ppb.BertTokenizer, 'bert-base-uncased')

# Load pretrained model/tokenizer
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

In [0]:
tokenized = df[0].apply((lambda x: tokenizer.encode(x, add_special_tokens=True)))
arr=[]
for i in tokenized:
  arr.append(np.array(i))
arr=np.array(arr)
print(arr)


[array([  101, 24095,  2097,  9585,  3403,  4734,  2011, 12398,  2000,
        2644, 24095,  5092, 14905,  2075,  1011,  6627, 26775,  4609,
        2818, 23221,  2213,  2003,  2437,  2070, 23956,  3431,   102])
 array([  101, 24095,  2097,  9585,  3403,  4734,  2011, 12398,  2000,
        2644, 24095,  5092, 14905,  2075,  1011,  6627, 26775,  4609,
        2818, 23221,  2213,  2003,  2437,  2070, 23956,  3431,  2000,
        4652, 25883,  6905,  2004, 27980,  2886,  7271,  1011,  4207,
        2678,  4455,  1012,  3225,  2258,  4833,  1010,  2009,  2097,
        5478, 20786,  2015,  2000,  4607,  4455,  3081,  3116,  8909,
        1010,  2144,  2122,  2089,  2022, 11445,  2030, 26513,  1012,
        5564,  1010,  2009,  2097,  2689,  7484,  3403,  4734,  2000,
        2022,  2006,  2011, 12398,  2061,  6184,  1012,  1012,  1012,
         102])
 array([  101, 12369, 14572,  1002,  1023,  1012,  1019,  2497,  4636,
        2000,  2393,  2490, 11103,  3316,  2083,  1996,  6090,  3207,
 

[[101,
  24095,
  2097,
  9585,
  3403,
  4734,
  2011,
  12398,
  2000,
  2644,
  24095,
  5092,
  14905,
  2075,
  1011,
  6627,
  26775,
  4609,
  2818,
  23221,
  2213,
  2003,
  2437,
  2070,
  23956,
  3431,
  2000,
  4652,
  25883,
  6905,
  2004,
  27980,
  2886,
  7271,
  1011,
  4207,
  2678,
  4455,
  1012,
  3225,
  2258,
  4833,
  1010,
  2009,
  2097,
  5478,
  20786,
  2015,
  2000,
  4607,
  4455,
  3081,
  3116,
  8909,
  1010,
  2144,
  2122,
  2089,
  2022,
  11445,
  2030,
  26513,
  1012,
  5564,
  1010,
  2009,
  2097,
  2689,
  7484,
  3403,
  4734,
  2000,
  2022,
  2006,
  2011,
  12398,
  2061,
  6184,
  1012,
  1012,
  1012,
  102],
 [101,
  12369,
  14572,
  1002,
  1023,
  1012,
  1019,
  2497,
  4636,
  2000,
  2393,
  2490,
  11103,
  3316,
  2083,
  1996,
  6090,
  3207,
  7712,
  1011,
  6627,
  26775,
  4609,
  2818,
  8545,
  1005,
  2128,
  2085,
  2195,
  3134,
  2046,
  2054,
  2038,
  2468,
  1037,
  2200,
  2502,
  16510,
  2005,
  1996,
  3795,


In [0]:
max_len = 0
for i in tokenized.values:
    if len(i) > max_len:
        max_len = len(i)

padded = np.array([i + [0]*(max_len-len(i)) for i in tokenized.values])


In [0]:
np.array(padded).shape

(1, 82)

In [0]:
attention_mask = np.where(padded != 0, 1, 0)
attention_mask.shape


(1, 82)

In [0]:
input_ids = torch.tensor(padded)  
attention_mask = torch.tensor(attention_mask)

with torch.no_grad():
    last_hidden_states = model(input_ids, attention_mask=attention_mask)

In [0]:
features = last_hidden_states[0][:,0,:].numpy()

In [0]:
features

array([[ 1.54340947e-02, -2.69571364e-01, -2.20665857e-02,
         7.71463588e-02,  6.93541691e-02, -4.85187829e-01,
         3.46923977e-01,  3.40789527e-01, -1.72755182e-01,
        -4.01167363e-01, -3.47896844e-01, -2.81589121e-01,
        -3.79683107e-01,  3.45565319e-01,  8.27954933e-02,
        -3.06378976e-02, -1.81475822e-02,  4.50143218e-01,
         2.19631031e-01,  7.48826787e-02, -2.03199610e-02,
        -3.02277178e-01,  5.30318245e-02, -3.87974679e-02,
         1.96245238e-01, -2.83734798e-01,  1.14129618e-01,
        -2.61708796e-01, -1.02246091e-01,  1.68469787e-01,
        -5.94027825e-02,  2.37075731e-01, -3.65067303e-01,
        -3.84853929e-01,  1.09148736e-03, -1.15446590e-01,
        -5.10895550e-02, -1.04318619e-01, -2.04456709e-02,
         2.46947482e-01, -2.33793586e-01,  1.87759742e-01,
        -1.59450341e-02,  8.73203352e-02,  6.00818582e-02,
        -5.51299304e-02, -2.61443186e+00, -4.11685668e-02,
        -3.82306837e-02, -5.49964249e-01, -6.06087372e-0

In [0]:
features.shape

(100, 768)

In [0]:
# For DistilBERT:



In [0]:
dinp=pd.DataFrame()
dinp.to_csv("dinp.csv")
with open('dinp.csv', 'w') as f:
    w = csv.writer(f, quoting=csv.QUOTE_ALL) 

    
    inp = input("enter the fact you wish to check")

    w.writerow([inp])
dinp=pd.read_csv("dinp.csv")
din=pd.DataFrame()
din=(dinp.columns)
print(din) #input from user


enter the fact you wish to checkZoom will enable waiting rooms by default to stop Zoombombing
Index(['Zoom will enable waiting rooms by default to stop Zoombombing'], dtype='object')


In [0]:
tokenized_inp=din.to_series().apply((lambda x: tokenizer.encode(x, add_special_tokens=True)))
print(tokenized_inp) #tokenizes the input from user

Zoom will enable waiting rooms by default to stop Zoombombing    [101, 24095, 2097, 9585, 3403, 4734, 2011, 123...
dtype: object


In [0]:


padded_inp = np.array([i + [0]*(max_len-len(i)) for i in tokenized_inp.values])
attention_mask_inp= np.where(padded_inp != 0, 1, 0)


In [0]:
input_ids = torch.tensor(padded_inp)  
attention_mask_inp = torch.tensor(attention_mask_inp)

with torch.no_grad():
    last_hidden_states_inp = model(input_ids, attention_mask=attention_mask_inp)

In [0]:
features_text = last_hidden_states_inp[0][:,0,:].numpy()

print(features_text.shape)

(1, 768)


In [0]:
padded.shape

(101, 97)

In [0]:
padded_inp.shape

(1, 97)

In [0]:
from sklearn.metrics.pairwise import cosine_similarity

In [0]:
cosine_similarity(padded, padded_inp)

array([[0.68524052],
       [0.48927903],
       [0.23523166],
       [0.21160068],
       [0.29978604],
       [0.30261005],
       [0.2788653 ],
       [0.30261005],
       [0.37748274],
       [0.18750838],
       [0.28648   ],
       [0.27416757],
       [0.13512844],
       [0.13030946],
       [0.30261005],
       [0.46058251],
       [0.35485799],
       [0.18750838],
       [0.33284823],
       [0.24987912],
       [0.46058251],
       [0.29978604],
       [0.43198486],
       [0.37748274],
       [0.27037073],
       [0.37369935],
       [0.13995447],
       [0.46058251],
       [0.37748274],
       [0.27530356],
       [0.2537928 ],
       [0.09212038],
       [0.26440028],
       [0.37176184],
       [0.20830517],
       [0.29505546],
       [0.201088  ],
       [0.24276736],
       [0.38275403],
       [0.38171319],
       [0.1969335 ],
       [0.28600145],
       [0.22519613],
       [0.15116754],
       [0.13895698],
       [0.30817408],
       [0.3832093 ],
       [0.438